USE taters;

INSERT INTO locations (barangay_name, municipality_name) 
VALUES
-- Manila
('Binondo', 'Manila'),
('Ermita', 'Manila'),
('Intramuros', 'Manila'),
('Malate', 'Manila'),
('Paco', 'Manila'),
('Pandacan', 'Manila'),
('Port Area', 'Manila'),
('Quiapo', 'Manila'),
('Sampaloc', 'Manila'),
('San Andres Bukid', 'Manila'),
('San Miguel', 'Manila'),
('San Nicolas', 'Manila'),
('Santa Ana', 'Manila'),
('Santa Cruz', 'Manila'),
('Santa Mesa', 'Manila'),
('Tondo', 'Manila'),

-- Caloocan
('Barangay 1', 'Caloocan'),
('Barangay 2', 'Caloocan'),
('Barangay 3', 'Caloocan'),
('Barangay 4', 'Caloocan'),
('Barangay 5', 'Caloocan'),
('Barangay 6', 'Caloocan'),
('Barangay 7', 'Caloocan'),
('Barangay 8', 'Caloocan'),
('Barangay 9', 'Caloocan'),
('Barangay 10', 'Caloocan'),
('Barangay 11', 'Caloocan'),
('Barangay 12', 'Caloocan'),
('Barangay 13', 'Caloocan'),
('Barangay 14', 'Caloocan'),
('Barangay 15', 'Caloocan'),
('Barangay 16', 'Caloocan'),
('Barangay 17', 'Caloocan'),
('Barangay 18', 'Caloocan'),
('Barangay 19', 'Caloocan'),
('Barangay 20', 'Caloocan'),
('Barangay 21', 'Caloocan'),
('Barangay 22', 'Caloocan'),
('Barangay 23', 'Caloocan'),
('Barangay 24', 'Caloocan'),
('Barangay 25', 'Caloocan'),
('Barangay 26', 'Caloocan'),
('Barangay 27', 'Caloocan'),
('Barangay 28', 'Caloocan'),
('Barangay 29', 'Caloocan'),
('Barangay 30', 'Caloocan'),
('Barangay 31', 'Caloocan'),
('Barangay 32', 'Caloocan'),
('Barangay 33', 'Caloocan'),
('Barangay 34', 'Caloocan'),
('Barangay 35', 'Caloocan'),
('Barangay 36', 'Caloocan'),
('Barangay 37', 'Caloocan'),
('Barangay 38', 'Caloocan'),
('Barangay 39', 'Caloocan'),
('Barangay 40', 'Caloocan'),
('Barangay 41', 'Caloocan'),
('Barangay 42', 'Caloocan'),
('Barangay 43', 'Caloocan'),
('Barangay 44', 'Caloocan'),
('Barangay 45', 'Caloocan'),
('Barangay 46', 'Caloocan'),
('Barangay 47', 'Caloocan'),
('Barangay 48', 'Caloocan'),
('Barangay 49', 'Caloocan'),
('Barangay 50', 'Caloocan'),
('Barangay 51', 'Caloocan'),
('Barangay 52', 'Caloocan'),
('Barangay 53', 'Caloocan'),
('Barangay 54', 'Caloocan'),
('Barangay 55', 'Caloocan'),
('Barangay 56', 'Caloocan'),
('Barangay 57', 'Caloocan'),
('Barangay 58', 'Caloocan'),
('Barangay 59', 'Caloocan'),
('Barangay 60', 'Caloocan'),
('Barangay 61', 'Caloocan'),
('Barangay 62', 'Caloocan'),
('Barangay 63', 'Caloocan'),
('Barangay 64', 'Caloocan'),
('Barangay 65', 'Caloocan'),
('Barangay 66', 'Caloocan'),
('Barangay 67', 'Caloocan'),
('Barangay 68', 'Caloocan'),
('Barangay 69', 'Caloocan'),
('Barangay 70', 'Caloocan'),
('Barangay 71', 'Caloocan'),
('Barangay 72', 'Caloocan'),
('Barangay 73', 'Caloocan'),
('Barangay 74', 'Caloocan'),
('Barangay 75', 'Caloocan'),
('Barangay 76', 'Caloocan'),
('Barangay 77', 'Caloocan'),
('Barangay 78', 'Caloocan'),
('Barangay 79', 'Caloocan'),
('Barangay 80', 'Caloocan'),
('Barangay 81', 'Caloocan'),
('Barangay 82', 'Caloocan'),
('Barangay 83', 'Caloocan'),
('Barangay 84', 'Caloocan'),
('Barangay 85', 'Caloocan'),
('Barangay 86', 'Caloocan'),
('Barangay 87', 'Caloocan'),
('Barangay 88', 'Caloocan'),
('Barangay 89', 'Caloocan'),
('Barangay 90', 'Caloocan'),
('Barangay 91', 'Caloocan'),
('Barangay 92', 'Caloocan'),
('Barangay 93', 'Caloocan'),
('Barangay 94', 'Caloocan'),
('Barangay 95', 'Caloocan'),
('Barangay 96', 'Caloocan'),
('Barangay 97', 'Caloocan'),
('Barangay 98', 'Caloocan'),
('Barangay 99', 'Caloocan'),
('Barangay 100', 'Caloocan'),
('Barangay 101', 'Caloocan'),
('Barangay 102', 'Caloocan'),
('Barangay 103', 'Caloocan'),
('Barangay 104', 'Caloocan'),
('Barangay 105', 'Caloocan'),
('Barangay 106', 'Caloocan'),
('Barangay 107', 'Caloocan'),
('Barangay 108', 'Caloocan'),
('Barangay 109', 'Caloocan'),
('Barangay 110', 'Caloocan'),
('Barangay 111', 'Caloocan'),
('Barangay 112', 'Caloocan'),
('Barangay 113', 'Caloocan'),
('Barangay 114', 'Caloocan'),
('Barangay 115', 'Caloocan'),
('Barangay 116', 'Caloocan'),
('Barangay 117', 'Caloocan'),
('Barangay 118', 'Caloocan'),
('Barangay 119', 'Caloocan'),
('Barangay 120', 'Caloocan'),
('Barangay 121', 'Caloocan'),
('Barangay 122', 'Caloocan'),
('Barangay 123', 'Caloocan'),
('Barangay 124', 'Caloocan'),
('Barangay 125', 'Caloocan'),
('Barangay 126', 'Caloocan'),
('Barangay 127', 'Caloocan'),
('Barangay 128', 'Caloocan'),
('Barangay 129', 'Caloocan'),
('Barangay 130', 'Caloocan'),
('Barangay 131', 'Caloocan'),
('Barangay 132', 'Caloocan'),
('Barangay 133', 'Caloocan'),
('Barangay 134', 'Caloocan'),
('Barangay 135', 'Caloocan'),
('Barangay 136', 'Caloocan'),
('Barangay 137', 'Caloocan'),
('Barangay 138', 'Caloocan'),
('Barangay 139', 'Caloocan'),
('Barangay 140', 'Caloocan'),
('Barangay 141', 'Caloocan'),
('Barangay 142', 'Caloocan'),
('Barangay 143', 'Caloocan'),
('Barangay 144', 'Caloocan'),
('Barangay 145', 'Caloocan'),
('Barangay 146', 'Caloocan'),
('Barangay 147', 'Caloocan'),
('Barangay 148', 'Caloocan'),
('Barangay 149', 'Caloocan'),
('Barangay 150', 'Caloocan'),
('Barangay 151', 'Caloocan'),
('Barangay 152', 'Caloocan'),
('Barangay 153', 'Caloocan'),
('Barangay 154', 'Caloocan'),
('Barangay 155', 'Caloocan'),
('Barangay 156', 'Caloocan'),
('Barangay 157', 'Caloocan'),
('Barangay 158', 'Caloocan'),
('Barangay 159', 'Caloocan'),
('Barangay 160', 'Caloocan'),
('Barangay 161', 'Caloocan'),
('Barangay 162', 'Caloocan'),
('Barangay 163', 'Caloocan'),
('Barangay 164', 'Caloocan'),
('Barangay 165', 'Caloocan'),
('Barangay 166', 'Caloocan'),
('Barangay 167', 'Caloocan'),
('Barangay 168', 'Caloocan'),
('Barangay 169', 'Caloocan'),
('Barangay 170', 'Caloocan'),
('Barangay 171', 'Caloocan'),
('Barangay 172', 'Caloocan'),
('Barangay 173', 'Caloocan'),
('Barangay 174', 'Caloocan'),
('Barangay 175', 'Caloocan'),
('Barangay 176', 'Caloocan'),
('Barangay 177', 'Caloocan'),
('Barangay 178', 'Caloocan'),
('Barangay 179', 'Caloocan'),
('Barangay 180', 'Caloocan'),
('Barangay 181', 'Caloocan'),
('Barangay 182', 'Caloocan'),
('Barangay 183', 'Caloocan'),
('Barangay 184', 'Caloocan'),
('Barangay 185', 'Caloocan'),
('Barangay 186', 'Caloocan'),
('Barangay 187', 'Caloocan'),
('Barangay 188', 'Caloocan'),

-- Las Piñas
('Almanza Dos', 'Las Piñas'),
('Almanza Uno', 'Las Piñas'),
('CAA-BF International', 'Las Piñas'),
('Daniel Fajardo', 'Las Piñas'),
('Elias Aldana', 'Las Piñas'),
('Ilaya', 'Las Piñas'),
('Manuyo Dos', 'Las Piñas'),
('Pamplona Dos', 'Las Piñas'),
('Pamplona Tres', 'Las Piñas'),
('Pulang Lupa Dos', 'Las Piñas'),
('Pulang Lupa Uno', 'Las Piñas'),
('Talon Dos', 'Las Piñas'),
('Talon Kuatro', 'Las Piñas'),
('Talon Singko', 'Las Piñas'),
('Talon Tres', 'Las Piñas'),
('Talon Uno', 'Las Piñas'),
('Zapote', 'Las Piñas'),

-- Makati
('Bangkal', 'Makati'),
('Bel-Air', 'Makati'),
('Carmona', 'Makati'),
('Cembo', 'Makati'),
('Comembo', 'Makati'),
('Dasmariñas', 'Makati'),
('East Rembo', 'Makati'),
('Forbes Park', 'Makati'),
('Guadalupe Nuevo', 'Makati'),
('Guadalupe Viejo', 'Makati'),
('Kasilawan', 'Makati'),
('La Paz', 'Makati'),
('Magallanes', 'Makati'),
('Olympia', 'Makati'),
('Palanan', 'Makati'),
('Pembo', 'Makati'),
('Pinagkaisahan', 'Makati'),
('Pio del Pilar', 'Makati'),
('Pitogo', 'Makati'),
('Poblacion', 'Makati'),
('Rizal', 'Makati'),
('San Antonio', 'Makati'),
('San Isidro', 'Makati'),
('San Lorenzo', 'Makati'),
('Santa Cruz', 'Makati'),
('Singkamas', 'Makati'),
('South Cembo', 'Makati'),
('Tejeros', 'Makati'),
('Urdaneta', 'Makati'),
('Valenzuela', 'Makati'),
('West Rembo', 'Makati'),

-- Malabon
('Acacia', 'Malabon'),
('Baritan', 'Malabon'),
('Bayan-Bayanan', 'Malabon'),
('Catmon', 'Malabon'),
('Concepcion', 'Malabon'),
('Dampalit', 'Malabon'),
('Flores', 'Malabon'),
('Hulong Duhat', 'Malabon'),
('Ibaba', 'Malabon'),
('Longos', 'Malabon'),
('Maysilo', 'Malabon'),
('Muzon', 'Malabon'),
('Niugan', 'Malabon'),
('Panghulo', 'Malabon'),
('Potrero', 'Malabon'),
('San Agustin', 'Malabon'),
('Santolan', 'Malabon'),
('Tañong', 'Malabon'),
('Tinajeros', 'Malabon'),
('Tonsuya', 'Malabon'),
('Tugatog', 'Malabon'),

-- Mandaluyong
('Bagong Silang', 'Mandaluyong'),
('Barangka Drive', 'Mandaluyong'),
('Barangka Ibaba', 'Mandaluyong'),
('Barangka Ilaya', 'Mandaluyong'),
('Barangka Itaas', 'Mandaluyong'),
('Buayang Bato', 'Mandaluyong'),
('Burol', 'Mandaluyong'),
('Daang Bakal', 'Mandaluyong'),
('Hagdang Bato Itaas', 'Mandaluyong'),
('Hagdang Bato Libis', 'Mandaluyong'),
('Harapin Ang Bukas', 'Mandaluyong'),
('Highway Hills', 'Mandaluyong'),
('Hulo', 'Mandaluyong'),
('Mabini-J. Rizal', 'Mandaluyong'),
('Malamig', 'Mandaluyong'),
('Namayan', 'Mandaluyong'),
('New Zañiga', 'Mandaluyong'),
('Pag-Asa', 'Mandaluyong'),
('Plainview', 'Mandaluyong'),
('Poblacion', 'Mandaluyong'),
('San Jose', 'Mandaluyong'),
('Vergara', 'Mandaluyong'),
('Wack-Wack Greenhills', 'Mandaluyong'),

-- Marikina
('Barangka', 'Marikina'),
('Concepcion Dos', 'Marikina'),
('Concepcion Uno', 'Marikina'),
('Fortune', 'Marikina'),
('Industrial Valley Complex', 'Marikina'),
('Jesus Dela Peña', 'Marikina'),
('Kalumpang', 'Marikina'),
('Malanday', 'Marikina'),
('Marikina Heights', 'Marikina'),
('Nangka', 'Marikina'),
('Parang', 'Marikina'),
('San Roque', 'Marikina'),
('Santa Elena', 'Marikina'),
('Santo Niño', 'Marikina'),
('Tañong', 'Marikina'),
('Tumana', 'Marikina'),

-- Muntinlupa
('Alabang', 'Muntinlupa'),
('Ayala Alabang', 'Muntinlupa'),
('Buli', 'Muntinlupa'),
('Cupang', 'Muntinlupa'),
('Poblacion', 'Muntinlupa'),
('Putatan', 'Muntinlupa'),
('Sucat', 'Muntinlupa'),
('Tunasan', 'Muntinlupa'),

-- Navotas
('Bagumbayan North', 'Navotas'),
('Bagumbayan South', 'Navotas'),
('Bangkulasi', 'Navotas'),
('Daanghari', 'Navotas'),
('Navotas East', 'Navotas'),
('Navotas West', 'Navotas'),
('North Bay Boulevard North', 'Navotas'),
('North Bay Boulevard South', 'Navotas'),
('San Jose', 'Navotas'),
('San Roque', 'Navotas'),
('Sipac-Almacen', 'Navotas'),
('Tangos North', 'Navotas'),
('Tangos South', 'Navotas'),
('Tanza', 'Navotas'),

-- Parañaque
('Baclaran', 'Parañaque'),
('BF Homes', 'Parañaque'),
('Don Bosco', 'Parañaque'),
('La Huerta', 'Parañaque'),
('Marcelo Green Village', 'Parañaque'),
('Merville', 'Parañaque'),
('Moonwalk', 'Parañaque'),
('San Antonio', 'Parañaque'),
('San Dionisio', 'Parañaque'),
('San Isidro', 'Parañaque'),
('San Martin de Porres', 'Parañaque'),
('Sun Valley', 'Parañaque'),
('Tambo', 'Parañaque'),
('Vitalez', 'Parañaque'),

-- Pasay
('Barangay 1', 'Pasay'),
('Barangay 201', 'Pasay'),

-- Pasig
('Bagong Ilog', 'Pasig'),
('Bagong Katipunan', 'Pasig'),
('Bambang', 'Pasig'),
('Buting', 'Pasig'),
('Caniogan', 'Pasig'),
('Dela Paz', 'Pasig'),
('Kalawaan', 'Pasig'),
('Kapasigan', 'Pasig'),
('Kapitolyo', 'Pasig'),
('Malinao', 'Pasig'),
('Manggahan', 'Pasig'),
('Maybunga', 'Pasig'),
('Oranbo', 'Pasig'),
('Palatiw', 'Pasig'),
('Pinagbuhatan', 'Pasig'),
('Pineda', 'Pasig'),
('Rosario', 'Pasig'),
('Sagad', 'Pasig'),
('San Joaquin', 'Pasig'),
('San Jose', 'Pasig'),
('San Miguel', 'Pasig'),
('Santa Cruz', 'Pasig'),
('Santa Lucia', 'Pasig'),
('Santa Rosa', 'Pasig'),
('Santo Tomas', 'Pasig'),
('Sumilang', 'Pasig'),
('Ugong', 'Pasig'),

-- Pateros
('Aguho', 'Pateros'),
('Magtanggol', 'Pateros'),
('Martires', 'Pateros'),
('Poblacion', 'Pateros'),
('San Pedro', 'Pateros'),
('San Roque', 'Pateros'),
('Santa Ana', 'Pateros'),
('Santo Rosario-Kanluran', 'Pateros'),
('Santo Rosario-Silangan', 'Pateros'),
('Tabacalera', 'Pateros'),

-- Quezon City
('Alicia', 'Quezon City'),
('Amihan', 'Quezon City'),
('Apolonio Samson', 'Quezon City'),
('Baesa', 'Quezon City'),
('Bagbag', 'Quezon City'),
('Bagong Pag-asa', 'Quezon City'),
('Bagong Silangan', 'Quezon City'),
('Bahay Toro', 'Quezon City'),
('Balingasa', 'Quezon City'),
('Batasan Hills', 'Quezon City'),
('Botocan', 'Quezon City'),
('Bungad', 'Quezon City'),
('Camp Aguinaldo', 'Quezon City'),
('Capri', 'Quezon City'),
('Central', 'Quezon City'),
('Claro', 'Quezon City'),
('Commonwealth', 'Quezon City'),
('Crame', 'Quezon City'),
('Damayan', 'Quezon City'),
('Dioquino Zobel', 'Quezon City'),
('Dona Aurora', 'Quezon City'),
('Doña Imelda', 'Quezon City'),
('Doña Josefa', 'Quezon City'),
('Duyan-Duyan', 'Quezon City'),
('E. Rodriguez', 'Quezon City'),
('East Kamias', 'Quezon City'),
('East Triangle', 'Quezon City'),
('Escopa I', 'Quezon City'),
('Escopa II', 'Quezon City'),
('Escopa III', 'Quezon City'),
('Escopa IV', 'Quezon City'),
('Fairview', 'Quezon City'),
('Greater Lagro', 'Quezon City'),
('Gulod', 'Quezon City'),
('Holy Spirit', 'Quezon City'),
('Horseshoe', 'Quezon City'),
('Immaculate Concepcion', 'Quezon City'),
('Kaligayahan', 'Quezon City'),
('Kalusugan', 'Quezon City'),
('Kamuning', 'Quezon City'),
('Katipunan', 'Quezon City'),
('Kaunlaran', 'Quezon City'),
('Kristong Hari', 'Quezon City'),
('Krus na Ligas', 'Quezon City'),
('Laging Handa', 'Quezon City'),
('Lahug', 'Quezon City'),
('Libis', 'Quezon City'),
('Loyola Heights', 'Quezon City'),
('Maharlika', 'Quezon City'),
('Malaya', 'Quezon City'),
('Mangga', 'Quezon City'),
('Manresa', 'Quezon City'),
('Mariana', 'Quezon City'),
('Mariblo', 'Quezon City'),
('Marilag', 'Quezon City'),
('Marilao', 'Quezon City'),
('Masagana', 'Quezon City'),
('Masambong', 'Quezon City'),
('Matandang Balara', 'Quezon City'),
('Milagrosa', 'Quezon City'),
('N.S. Amoranto', 'Quezon City'),
('Nagkaisang Nayon', 'Quezon City'),
('Nayon Kaunlaran', 'Quezon City'),
('New Era', 'Quezon City'),
('North Fairview', 'Quezon City'),
('Novaliches Proper', 'Quezon City'),
('Obrero', 'Quezon City'),
('Old Capitol Site', 'Quezon City'),
('Paligsahan', 'Quezon City'),
('Pasong Putik', 'Quezon City'),
('Pasong Tamo', 'Quezon City'),
('Payatas', 'Quezon City'),
('Phil-Am', 'Quezon City'),
('Pinagkaisahan', 'Quezon City'),
('Project 6', 'Quezon City'),
('Quirino 2A', 'Quezon City'),
('Quirino 2B', 'Quezon City'),
('Quirino 3A', 'Quezon City'),
('Quirino 3B', 'Quezon City'),
('Ramon Magsaysay', 'Quezon City'),
('Roxas', 'Quezon City'),
('Sacred Heart', 'Quezon City'),
('San Agustin', 'Quezon City'),
('San Antonio', 'Quezon City'),
('San Bartolome', 'Quezon City'),
('San Isidro', 'Quezon City'),
('San Jose', 'Quezon City'),
('San Martin de Porres', 'Quezon City'),
('San Roque', 'Quezon City'),
('San Vicente', 'Quezon City'),
('Santa Cruz', 'Quezon City'),
('Santa Lucia', 'Quezon City'),
('Santa Monica', 'Quezon City'),
('Santa Teresita', 'Quezon City'),
('Santo Cristo', 'Quezon City'),
('Santo Domingo', 'Quezon City'),
('Santol', 'Quezon City'),
('Sikatuna Village', 'Quezon City'),
('Silangan', 'Quezon City'),
('Socorro', 'Quezon City'),
('South Triangle', 'Quezon City'),
('Tagumpay', 'Quezon City'),
('Talayan', 'Quezon City'),
('Talipapa', 'Quezon City'),
('Tandang Sora', 'Quezon City'),
('Tatalon', 'Quezon City'),
('Teachers Village East', 'Quezon City'),
('Teachers Village West', 'Quezon City'),
('U.P. Campus', 'Quezon City'),
('U.P. Village', 'Quezon City'),
('Ugong Norte', 'Quezon City'),
('Unang Sigaw', 'Quezon City'),
('Vasra', 'Quezon City'),
('Veterans Village', 'Quezon City'),
('Villa Maria Clara', 'Quezon City'),
('West Kamias', 'Quezon City'),
('West Triangle', 'Quezon City'),
('White Plains', 'Quezon City'),

-- San Juan
('Addition Hills', 'San Juan'),
('Balong Bato', 'San Juan'),
('Batis', 'San Juan'),
('Corazon de Jesus', 'San Juan'),
('Ermitaño', 'San Juan'),
('Greenhills', 'San Juan'),
('Isabelita', 'San Juan'),
('Kabayanan', 'San Juan'),
('Little Baguio', 'San Juan'),
('Maytunas', 'San Juan'),
('Onse', 'San Juan'),
('Pasadena', 'San Juan'),
('Pedro Cruz', 'San Juan'),
('Progreso', 'San Juan'),
('Rivera', 'San Juan'),
('Salapan', 'San Juan'),
('San Perfecto', 'San Juan'),
('Santa Lucia', 'San Juan'),
('Tibagan', 'San Juan'),
('West Crame', 'San Juan'),

-- Taguig
('Bagumbayan', 'Taguig'),
('Bambang', 'Taguig'),
('Calzada', 'Taguig'),
('Hagonoy', 'Taguig'),
('Ibayo-Tipas', 'Taguig'),
('Ligid-Tipas', 'Taguig'),
('Lower Bicutan', 'Taguig'),
('Napindan', 'Taguig'),
('New Lower Bicutan', 'Taguig'),
('Palingon-Tipas', 'Taguig'),
('Pinagsama', 'Taguig'),
('San Miguel', 'Taguig'),
('Santa Ana', 'Taguig'),
('Tuktukan', 'Taguig'),
('Upper Bicutan', 'Taguig'),
('Ususan', 'Taguig'),
('Wawa', 'Taguig'),
('Western Bicutan', 'Taguig'),

-- Valenzuela
('Arkong Bato', 'Valenzuela'),
('Bagbaguin', 'Valenzuela'),
('Balangkas', 'Valenzuela'),
('Bignay', 'Valenzuela'),
('Bisig', 'Valenzuela'),
('Canumay East', 'Valenzuela'),
('Canumay West', 'Valenzuela'),
('Coloong', 'Valenzuela'),
('Dalandanan', 'Valenzuela'),
('Gen. T. De Leon', 'Valenzuela'),
('Isla', 'Valenzuela'),
('Karuhatan', 'Valenzuela'),
('Lawang Bato', 'Valenzuela'),
('Lingunan', 'Valenzuela'),
('Mabolo', 'Valenzuela'),
('Malanday', 'Valenzuela'),
('Malinta', 'Valenzuela'),
('Mapulang Lupa', 'Valenzuela'),
('Marulas', 'Valenzuela'),
('Maysan', 'Valenzuela'),
('Palasan', 'Valenzuela'),
('Parada', 'Valenzuela'),
('Paso de Blas', 'Valenzuela'),
('Pasolo', 'Valenzuela'),
('Poblacion', 'Valenzuela'),
('Polo', 'Valenzuela'),
('Rincon', 'Valenzuela'),
('Tagalag', 'Valenzuela'),
('Ugong', 'Valenzuela'),
('Veinte Reales', 'Valenzuela'),
('Wawang Pulo', 'Valenzuela');

